### ISSUE TITLE
will forge (and similar) be supported?

### ISSUE THREAD

**Issue by rlesch** [Alex2772/hackers-mc-launcher#2]
currently it seems it doesnt work with forge, at least 1.15.2 with forge just doesnt load at all and it seems most of cmd arguments are just missing.

**Comment by Alex2772** [comment]
All versions of Forge including 1.15.2 are working in hackers mc. Looks like they again changed JSON format. Minecraft 1.15.2 is not starting after installation of Forge.

**Comment by Alex2772** [comment]
Fixed. Please do not forget to reset profile before testing, since launcher stores some information in it's cache. In your case cache contains invalid information, so "Reset profile" button will fix this.
